version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tasks
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Explicit port exposure
    healthcheck:  # Added health check
      test: ["CMD-SHELL", "pg_isready -U postgres -d tasks"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - todo-network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432  # Added missing environment variables
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: tasks
    depends_on:
      db:
        condition: service_healthy  # Wait for healthy DB
    networks:
      - todo-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
     - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8080
    networks:
      - todo-network

networks:
  todo-network:

volumes:
  postgres_data: